using System.Text;
using ArIED61850Tester.Models;
using ArIED61850Tester.Models.IoTesting;
using ArIED61850Tester.Services.IoTesting;

namespace ARSAS.Tests;

public sealed class IoFatProfessionalReportRegressionTests
{
    [Fact]
    public void ReportLayout_UsesCustomerFacingFooterAndOmitsEmptySourceHashPlaceholder()
    {
        var project = Project("IED-A", "192.0.2.10");
        var layout = IoFatPdfReportService.BuildLayout(
            project,
            new DateTimeOffset(2026, 9, 7, 0, 0, 0, TimeSpan.Zero));
        var text = string.Join("\n", layout.Pages
            .SelectMany(page => page.Commands)
            .OfType<IoFatReportTextCommand>()
            .Select(command => command.Text));

        Assert.Contains("Automatically generated by ARSAS Protocol Tester", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Source SHA-256 -", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Generated 2026", text, StringComparison.Ordinal);
    }

    [Fact]
    public void NativePdf_EmbedsOneUnifiedInterOrSegoeTypefaceInsteadOfBase14Fonts()
    {
        var bytes = IoFatPdfReportService.Generate(Project("IED-A", "192.0.2.10"));
        var pdf = Encoding.Latin1.GetString(bytes);

        Assert.Contains("/Subtype /TrueType", pdf, StringComparison.Ordinal);
        Assert.Contains("/FontFile2", pdf, StringComparison.Ordinal);
        Assert.DoesNotContain("/BaseFont /Helvetica", pdf, StringComparison.Ordinal);
        Assert.DoesNotContain("/BaseFont /Courier", pdf, StringComparison.Ordinal);
        Assert.DoesNotContain("/F3 ", pdf, StringComparison.Ordinal);
    }

    [Fact]
    public void PerIedStop_LeavesSiblingFatSessionRunning()
    {
        var project = new IoTestProject
        {
            ProjectId = "P-PER-IED",
            SchemaVersion = "ARSAS-FAT-SCL-1.0",
            ProjectName = "Per IED evidence",
            Ieds =
            {
                Ied("IED-A", "192.0.2.10"),
                Ied("IED-B", "192.0.2.11")
            }
        };
        var devices = project.Ieds.Select((ied, index) => Device(ied, index + 1)).ToArray();
        new IoTestLiveBindingService().Bind(project, devices);
        var root = TempDirectory();
        Iec61850MonitorDevice? Resolve(string key) => devices.FirstOrDefault(device =>
            key.Equals(device.DeviceId, StringComparison.OrdinalIgnoreCase) ||
            key.Equals(device.Name, StringComparison.OrdinalIgnoreCase) ||
            key.Equals(device.IpAddress, StringComparison.OrdinalIgnoreCase));

        var primary = new IoTestSessionController(project, Resolve, action => action(), root);
        using var coordinator = new IoTestMultiSessionCoordinator(project, primary);
        coordinator.ConfigureSiblingFactory(() => new IoTestSessionController(project, Resolve, action => action(), root));

        Assert.True(coordinator.Start(project.Ieds[0]).Succeeded);
        Assert.True(coordinator.Start(project.Ieds[1]).Succeeded);
        Assert.Equal(2, coordinator.ActiveSessionCount);

        coordinator.SelectContext(project.Ieds[0]);
        var stoppedA = coordinator.Stop("targeted test stop");

        Assert.True(stoppedA.Succeeded, stoppedA.Message);
        Assert.False(coordinator.IsIedSessionActive(project.Ieds[0]));
        Assert.True(coordinator.IsIedSessionActive(project.Ieds[1]));
        Assert.Equal(1, coordinator.ActiveSessionCount);
        coordinator.SelectContext(project.Ieds[1]);
        Assert.True(coordinator.Stop("cleanup").Succeeded);
    }

    [Fact]
    public void ProfessionalPreviewUx_UsesLucideVectorsAndExplicitSavePdfLabel()
    {
        var source = File.ReadAllText(FindRepoFile("IoListTestingWindow.ProfessionalReportUx.cs"));

        Assert.Contains("PreviewLucideIcon.FileDown", source, StringComparison.Ordinal);
        Assert.Contains("\"Save PDF\"", source, StringComparison.Ordinal);
        Assert.Contains("PreviewLucideIcon.X", source, StringComparison.Ordinal);
        Assert.Contains("StopIedSessionWithoutChangingExplorer", source, StringComparison.Ordinal);
        Assert.Contains("Other IED FAT sessions may remain active", source, StringComparison.Ordinal);
    }

    [Fact]
    public void TypographyPolicy_IsInterFirstWithOnlySegoeUiFallbackForReportText()
    {
        Assert.Equal("Inter", IoFatReportTypography.PreferredFamilyName);
        Assert.Equal("Segoe UI", IoFatReportTypography.FallbackFamilyName);
        Assert.Equal("Inter, Segoe UI", IoFatReportTypography.PreviewFontFamily.Source);
    }

    private static IoTestProject Project(string name, string ip)
        => new()
        {
            ProjectId = "P-REPORT",
            SchemaVersion = "ARSAS-FAT-SCL-1.0",
            ProjectName = "Professional FAT report",
            Ieds = { Ied(name, ip) }
        };

    private static IoTestIedPlan Ied(string name, string ip)
    {
        var point = new IoTestPointPlan
        {
            TestPointId = $"{name}-P1",
            IedName = name,
            IpAddress = ip,
            SignalName = "Breaker healthy",
            ObjectReference = $"{name}ADD/GGIO1.CBHealthy",
            FunctionalConstraint = "ST",
            ExpectedOnText = "True",
            ExpectedOffText = "False",
            DataType = "BOOLEAN",
            SignalKind = FatSignalKind.Discrete,
            CaptureMode = FatCaptureMode.AutomaticTransition,
            ImportReady = true,
            BindingStatus = "SCL_DATASET_AUTHORITY"
        };
        return new IoTestIedPlan
        {
            IedName = name,
            IpAddress = ip,
            TestPoints = { point }
        };
    }

    private static Iec61850MonitorDevice Device(IoTestIedPlan ied, int sequence)
    {
        var point = ied.TestPoints[0];
        var device = new Iec61850MonitorDevice
        {
            DeviceId = $"device-{sequence}",
            Name = ied.IedName,
            SclIedName = ied.IedName,
            IpAddress = ied.IpAddress,
            Port = 102,
            IsConnected = true,
            IsMonitoring = true,
            Status = "Monitoring"
        };
        device.Points.Add(new Iec61850MonitorPoint
        {
            DeviceId = device.DeviceId,
            DeviceName = device.Name,
            IpAddress = device.IpAddress,
            SignalName = point.SignalName,
            IecReference = point.ObjectReference,
            FunctionalConstraint = point.FunctionalConstraint,
            Value = "False",
            Quality = "Good",
            DeviceTimestamp = "2026-09-07T00:00:00.000Z",
            SourceMode = "BRCB",
            Sequence = sequence,
            Status = "Live"
        });
        return device;
    }

    private static string TempDirectory()
    {
        var path = Path.Combine(Path.GetTempPath(), "ARSAS.Tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static string FindRepoFile(string relativePath)
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current != null)
        {
            var candidate = Path.Combine(current.FullName, relativePath);
            if (File.Exists(candidate))
                return candidate;
            current = current.Parent;
        }
        throw new FileNotFoundException($"Could not locate repository file '{relativePath}'.");
    }
}
