using System.Text;
using ArIED61850Tester.Models.IoTesting;
using ArIED61850Tester.Services.IoTesting;

namespace ARSAS.Tests;

public sealed class IoFatExecutiveReportLayoutTests
{
    [Fact]
    public void ExecutivePdf_UntestedScopeIsBlankCustomerReviewFormWithoutResultCounters()
    {
        var project = BuildProject("IFAT SCOPE UPDATED", "Operated", "Normal");

        var bytes = IoFatPdfReportService.Generate(
            project,
            new DateTimeOffset(2026, 7, 30, 14, 0, 0, TimeSpan.FromHours(7)));
        var text = Encoding.ASCII.GetString(bytes);

        Assert.StartsWith("%PDF-1.4", text, StringComparison.Ordinal);
        Assert.Contains("V-2181-801-A-EIC-154", text, StringComparison.Ordinal);
        Assert.Contains("REV 02", text, StringComparison.Ordinal);
        Assert.Contains("FOR CUSTOMER REVIEW", text, StringComparison.Ordinal);
        Assert.Contains("BLANK IFAT TEST FORM", text, StringComparison.Ordinal);
        Assert.Contains("PLANNED SIGNALS 1", text, StringComparison.Ordinal);
        Assert.Contains("NOT STARTED", text, StringComparison.Ordinal);
        Assert.DoesNotContain("PASS 0", text, StringComparison.Ordinal);
        Assert.DoesNotContain("PENDING 1", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Testing is incomplete", text, StringComparison.Ordinal);
        Assert.DoesNotContain("CUSTOMER FAT RECORD", text, StringComparison.Ordinal);
        Assert.Contains("ADD/GGIO6.CBOpnd", text, StringComparison.Ordinal);
        Assert.Contains("APPENDIX A - PLANNED IEC 61850 IFAT CHECKS", text, StringComparison.Ordinal);
        Assert.Contains("CUSTOMER REVIEWER", text, StringComparison.Ordinal);
        Assert.Contains("Auto-generated by ARSAS IEC 61850 Protocol Tester", text, StringComparison.Ordinal);
        Assert.Contains("To be completed during IFAT", text, StringComparison.Ordinal);
    }

    [Fact]
    public void ExecutivePdf_StartedButIncompleteScopeBecomesPartialTestRecord()
    {
        var project = BuildProject("IFAT EXECUTION", "Operated", "Normal");
        Start(project.Ieds[0].TestPoints[0]);

        var text = Encoding.ASCII.GetString(IoFatPdfReportService.Generate(project));

        Assert.Contains("PARTIAL", text, StringComparison.Ordinal);
        Assert.Contains("NOT FOR CUSTOMER ACCEPTANCE", text, StringComparison.Ordinal);
        Assert.Contains("APPENDIX A - DETAILED IEC 61850 SIGNAL EVIDENCE", text, StringComparison.Ordinal);
        Assert.DoesNotContain("BLANK IFAT TEST FORM", text, StringComparison.Ordinal);
    }

    [Fact]
    public void ExecutivePdf_AllPassedScopeIsAsTestedAndContainsTransitionTraceability()
    {
        var project = BuildProject("READY FOR FAT", "Operated", "Normal");
        Complete(project.Ieds[0].TestPoints[0]);

        var text = Encoding.ASCII.GetString(IoFatPdfReportService.Generate(project));

        Assert.Contains("AS TESTED", text, StringComparison.Ordinal);
        Assert.Contains("CUSTOMER FAT RECORD", text, StringComparison.Ordinal);
        Assert.Contains("PT Siemens Indonesia", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Package:", text, StringComparison.Ordinal);
        Assert.Contains("ARSAS:", text, StringComparison.Ordinal);
        Assert.Contains("Quality: Good", text, StringComparison.Ordinal);
        Assert.Contains("Source: BRCB", text, StringComparison.Ordinal);
        Assert.Contains("Seq: 2 / Gen: 1", text, StringComparison.Ordinal);
    }

    [Fact]
    public void ExecutivePdf_ReplacesUnknownSourceStateLabelsWithBooleanStates()
    {
        var project = BuildProject("REVIEW REQUIRED", "TBA", "N/A");

        var bytes = IoFatPdfReportService.Generate(project);
        var text = Encoding.ASCII.GetString(bytes);

        Assert.Contains("TRUE", text, StringComparison.Ordinal);
        Assert.Contains("FALSE", text, StringComparison.Ordinal);
        Assert.DoesNotContain("TBA (True)", text, StringComparison.Ordinal);
        Assert.DoesNotContain("N/A (False)", text, StringComparison.Ordinal);
    }

    [Fact]
    public void ExecutiveLayoutContract_IsCleanButAuditDefensible()
    {
        var source = File.ReadAllText(FindRepoFile("Services/IoTesting/IoFatExecutiveReportLayoutEngine.cs"));
        var preview = File.ReadAllText(FindRepoFile("Services/IoTesting/IoFatReportPreviewDocumentBuilder.cs"));

        Assert.Contains("IEC 61850 / event-log reference", source, StringComparison.Ordinal);
        Assert.Contains("point.ReportIecReference", source, StringComparison.Ordinal);
        Assert.Contains("DOCUMENT CONTROL", source, StringComparison.Ordinal);
        Assert.Contains("FALSE > TRUE > FALSE", source, StringComparison.Ordinal);
        Assert.Contains("TESTED BY", source, StringComparison.Ordinal);
        Assert.Contains("CHECKED BY", source, StringComparison.Ordinal);
        Assert.Contains("CLIENT WITNESS", source, StringComparison.Ordinal);
        Assert.Contains("APPROVED BY", source, StringComparison.Ordinal);
        Assert.Contains("yyyy-MM-dd HH:mm:ss.fff", source, StringComparison.Ordinal);
        Assert.Contains("IoFatReportFontKind.Bold, 16.8d", source, StringComparison.Ordinal);
        Assert.Contains("The ARSAS result state controls this PDF classification", source, StringComparison.Ordinal);
        Assert.Contains("NOT FOR CUSTOMER ACCEPTANCE", source, StringComparison.Ordinal);
        Assert.Contains("APPENDIX A - DETAILED IEC 61850 SIGNAL EVIDENCE", source, StringComparison.Ordinal);
        Assert.Contains("APPENDIX A - PLANNED IEC 61850 IFAT CHECKS", source, StringComparison.Ordinal);
        Assert.Contains("FOR CUSTOMER REVIEW", source, StringComparison.Ordinal);
        Assert.Contains("BLANK IFAT TEST FORM", source, StringComparison.Ordinal);
        Assert.Contains("Auto-generated by ARSAS IEC 61850 Protocol Tester", source, StringComparison.Ordinal);
        Assert.Contains("ARSAS capture time and sequence are the ordering authority", source, StringComparison.Ordinal);
        Assert.Contains("SUPPLEMENTARY RELAY TESTS", source, StringComparison.Ordinal);
        Assert.Contains("SNTP/NTP, PTP/IEEE 1588, IRIG-B", source, StringComparison.Ordinal);
        Assert.Contains("does not set the relay clock or act as an SNTP server", source, StringComparison.Ordinal);
        Assert.Contains("COMTRADE / disturbance recording", source, StringComparison.Ordinal);
        Assert.Contains("BCU and other devices without that service are reported as N/A", source, StringComparison.Ordinal);
        Assert.True(File.Exists(FindRepoFile("docs/RELAY_TIME_SYNC_AND_DISTURBANCE_TEST.md")));
        Assert.Contains("Inter, Segoe UI, Aptos, Arial", preview, StringComparison.Ordinal);
        Assert.DoesNotContain("DEVICE RESULT", source, StringComparison.Ordinal);
        Assert.DoesNotContain("reviewIssue", source, StringComparison.Ordinal);
        Assert.DoesNotContain("CharacterEllipsis", source, StringComparison.Ordinal);
        Assert.DoesNotContain(" + \"...\"", source, StringComparison.Ordinal);
    }

    private static IoTestProject BuildProject(string issueStatus, string expectedOn, string expectedOff) => new()
    {
        ProjectId = "UCC-2181801A-E99-0001",
        SchemaVersion = IoTestImportValidator.SupportedSchemaVersion,
        ProjectName = "Tangguh UCC Project - Onshore EPCI",
        SourceWorkbookName = "IEC61850_FAT_Import_Rev3_EventLogReady.xlsx",
        SourceWorkbookSha256 = new string('a', 64),
        DocumentControl = new IoFatDocumentControl
        {
            ClientProject = "Tangguh UCC Project - Onshore EPCI",
            SupplierName = "PT Siemens Indonesia",
            PurchaseOrderTitle = "Power Management System (PMS)",
            PurchaserDocumentNumber = "V-2181-801-A-EIC-154",
            CompanyProjectDocumentNumber = "UCC-2181801A-E99-0001",
            Revision = "02",
            IssueStatus = issueStatus
        },
        Ieds =
        [
            new IoTestIedPlan
            {
                IedName = "AA1C1F03R4",
                IpAddress = "192.168.81.70",
                IedRole = "BCU - 6MD85",
                Location = "ELECT-CCPP",
                VoltageLevel = "66kV",
                Switchgear = "261-SWG-51001",
                PanelTag = "261-CRP-51216 / F00+R1",
                TestPoints =
                [
                    new IoTestPointPlan
                    {
                        TestPointId = "UCC-IEC-0001",
                        IedName = "AA1C1F03R4",
                        IpAddress = "192.168.81.70",
                        SignalName = "CB opened",
                        ObjectReference = "AA1C1F03R4Application/ADD/GGIO6.CBOpnd.stVal",
                        FunctionalConstraint = "ST",
                        SourceIecReference = "ADD/GGIO6.CBOpnd",
                        EventLogSearchReference = "ADD/GGIO6.CBOpnd",
                        ExpectedOnText = expectedOn,
                        ExpectedOffText = expectedOff,
                        TestEnabled = true,
                        ImportReady = true
                    }
                ]
            }
        ]
    };

    private static void Complete(IoTestPointPlan point)
    {
        var evaluator = new IoTestTransitionEvaluator();
        evaluator.StartAttempt(point, Observation(false, 1));
        evaluator.Observe(point, Observation(true, 2));
        evaluator.Observe(point, Observation(false, 3));
    }

    private static void Start(IoTestPointPlan point)
    {
        new IoTestTransitionEvaluator().StartAttempt(point, Observation(false, 1));
    }

    private static IoTestObservation Observation(bool state, long sequence)
    {
        var captured = new DateTimeOffset(2026, 8, 11, 8, 0, 0, TimeSpan.Zero).AddMilliseconds(sequence * 100);
        return new IoTestObservation(state, state ? "true" : "false", captured, captured.AddMilliseconds(-5), "Good", "BRCB", sequence, 1);
    }

    private static string FindRepoFile(string relativePath)
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory != null)
        {
            var candidate = Path.Combine(directory.FullName, relativePath);
            if (File.Exists(candidate))
                return candidate;
            directory = directory.Parent;
        }
        throw new FileNotFoundException($"Could not locate repository file '{relativePath}' from '{AppContext.BaseDirectory}'.");
    }
}
