version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      test-tooling:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit"
          - "xunit.runner.visualstudio"
