using ArIED61850Tester.Models.IoTesting;

namespace ArIED61850Tester.Services.IoTesting;

/// <summary>
/// Native report layout for SCL-backed FAT v2. IEC references are never truncated: long
/// references wrap inside a variable-height row so the FC/DO/DA tail remains auditable in
/// both WPF Print Preview and the native PDF report.
/// </summary>
internal static class IoFatV2ReportLayoutEngine
{
    public const double PageWidth = 842d;
    public const double PageHeight = 595d;

    private const double Margin = 30d;
    private const double ContentTop = 488d;
    private const double ContentBottom = 54d;
    private const double MinimumRowHeight = 36d;
    private const int ReferenceCharsPerLine = 56;

    private static readonly IoFatReportColor Navy = Color("0F172A");
    private static readonly IoFatReportColor Blue = Color("2563EB");
    private static readonly IoFatReportColor SoftBlue = Color("EFF6FF");
    private static readonly IoFatReportColor Border = Color("DCE5F0");
    private static readonly IoFatReportColor Ink = Color("243146");
    private static readonly IoFatReportColor Muted = Color("64748B");
    private static readonly IoFatReportColor EvidenceMuted = Color("52627A");
    private static readonly IoFatReportColor White = Color("FFFFFF");
    private static readonly IoFatReportColor Pass = Color("15803D");
    private static readonly IoFatReportColor Attention = Color("B45309");
    private static readonly IoFatReportColor Fail = Color("B91C1C");

    // Wider IEC-reference column is intentional. Total remains the 782 pt content width.
    private static readonly double[] Widths = [24d, 115d, 280d, 60d, 105d, 105d, 93d];

    public static IoFatReportLayoutPlan Build(IoTestProject project, DateTimeOffset created, bool draft = false)
    {
        ArgumentNullException.ThrowIfNull(project);
        var pages = new List<List<IoFatReportCommand>>();
        var page = NewPage(pages, project, created, draft);
        var y = ContentTop;

        foreach (var ied in project.Ieds)
        {
            var points = ied.TestPoints.Where(point => point.IsIncludedInFat).ToArray();
            Ensure(ref page, ref y, pages, project, created, draft, 56d);
            DrawIedHeader(page, ied, points, ref y);
            DrawTableHeader(page, ref y);

            var row = 0;
            foreach (var point in points)
            {
                row++;
                var rowHeight = GetPointRowHeight(point);
                if (y - rowHeight < ContentBottom)
                {
                    page = NewPage(pages, project, created, draft);
                    y = ContentTop;
                    DrawIedHeader(page, ied, points, ref y, continued: true);
                    DrawTableHeader(page, ref y);
                }
                DrawPointRow(page, point, row, rowHeight, ref y);
            }
            y -= 12d;
        }

        if (project.Ieds.Count == 0)
        {
            page.Add(new IoFatReportTextCommand(Margin, y - 18d, 600d, "No FAT IED is present in this project.", IoFatReportFontKind.Bold, 9d, Attention));
        }

        for (var index = 0; index < pages.Count; index++)
        {
            pages[index].Add(new IoFatReportLineCommand(Margin, 42d, PageWidth - Margin, 42d, Border, 0.6d));
            pages[index].Add(new IoFatReportTextCommand(Margin, 24d, 430d,
                $"Automatically generated by ARSAS Protocol Tester · {created:yyyy-MM-dd HH:mm:ss zzz}",
                IoFatReportFontKind.Regular, 6.2d, Muted));
            if (!string.IsNullOrWhiteSpace(project.SourceSetSha256))
            {
                pages[index].Add(new IoFatReportTextCommand(Margin + 438d, 24d, 210d,
                    $"Source SHA-256 {Short(project.SourceSetSha256, 20)}",
                    IoFatReportFontKind.Regular, 6.2d, Muted));
            }
            pages[index].Add(new IoFatReportTextCommand(PageWidth - Margin - 100d, 24d, 100d,
                $"Page {index + 1} / {pages.Count}", IoFatReportFontKind.Regular, 6.2d, Muted));
        }

        return new IoFatReportLayoutPlan(
            project.ProjectId,
            created,
            draft,
            pages.Select((commands, index) =>
                new IoFatReportPagePlan(index + 1, PageWidth, PageHeight, commands.ToArray())).ToArray());
    }

    private static List<IoFatReportCommand> NewPage(
        List<List<IoFatReportCommand>> pages,
        IoTestProject project,
        DateTimeOffset created,
        bool draft)
    {
        var page = new List<IoFatReportCommand>();
        pages.Add(page);
        page.Add(new IoFatReportTextCommand(Margin, 566d, 520d,
            Clean(project.ProjectName), IoFatReportFontKind.Bold, 7.2d, Muted));
        page.Add(new IoFatReportTextCommand(Margin, 544d, 520d,
            "IEC 61850 FAT Evidence Report", IoFatReportFontKind.Bold, 16.8d, Navy));
        page.Add(new IoFatReportTextCommand(Margin, 524d, 560d,
            "Static DataSet verification · generic Value 1 / Value 2 evidence · source identity preserved",
            IoFatReportFontKind.Regular, 7.8d, Muted));
        page.Add(new IoFatReportRectCommand(PageWidth - Margin - 190d, 568d, 190d, 54d, 4d, SoftBlue, Border, 0.7d));
        page.Add(new IoFatReportTextCommand(PageWidth - Margin - 178d, 550d, 166d,
            "FAT REPORT", IoFatReportFontKind.Bold, 7.2d, Blue));
        page.Add(new IoFatReportTextCommand(PageWidth - Margin - 178d, 534d, 166d,
            "FOR FAT RECORD",
            IoFatReportFontKind.Regular, 6.4d, Ink));
        page.Add(new IoFatReportLineCommand(Margin, 504d, PageWidth - Margin, 504d, Border, 0.8d));
        return page;
    }

    private static void Ensure(
        ref List<IoFatReportCommand> page,
        ref double y,
        List<List<IoFatReportCommand>> pages,
        IoTestProject project,
        DateTimeOffset created,
        bool draft,
        double height)
    {
        if (y - height >= ContentBottom)
            return;
        page = NewPage(pages, project, created, draft);
        y = ContentTop;
    }

    private static void DrawIedHeader(
        List<IoFatReportCommand> page,
        IoTestIedPlan ied,
        IReadOnlyCollection<IoTestPointPlan> points,
        ref double y,
        bool continued = false)
    {
        var complete = points.Count(point => point.IsFatEvidenceComplete);
        var digitalPass = points.Count(point =>
            point.CaptureMode == FatCaptureMode.AutomaticTransition &&
            point.Runtime.State == IoTestPointState.Passed);
        var manualComplete = points.Count(point =>
            point.CaptureMode == FatCaptureMode.OperatorSnapshot && point.IsFatEvidenceComplete);
        var title = continued ? $"{ied.IedName} (continued)" : ied.IedName;
        page.Add(new IoFatReportRectCommand(Margin, y, 4d, 38d, 0d, Blue, Blue, 0d));
        page.Add(new IoFatReportTextCommand(Margin + 14d, y - 14d, 380d, Clean(title), IoFatReportFontKind.Bold, 10.2d, Navy));
        page.Add(new IoFatReportTextCommand(Margin + 14d, y - 29d, 420d,
            string.IsNullOrWhiteSpace(ied.IpAddress) ? "Offline SCL scope · endpoint not bound" : Clean(ied.IpAddress),
            IoFatReportFontKind.Regular, 6.5d, Muted));
        page.Add(new IoFatReportTextCommand(PageWidth - Margin - 300d, y - 28d, 290d,
            $"{complete}/{points.Count} complete · {digitalPass} digital PASS · {manualComplete} snapshot complete",
            IoFatReportFontKind.Bold, 6.7d, complete == points.Count && points.Count > 0 ? Pass : Blue));
        y -= 46d;
    }

    private static void DrawTableHeader(List<IoFatReportCommand> page, ref double y)
    {
        var headers = new[] { "#", "Signal", "IEC 61850 reference", "Type", "Value 1", "Value 2", "Result" };
        var x = Margin;
        const double height = 22d;
        for (var index = 0; index < headers.Length; index++)
        {
            page.Add(new IoFatReportRectCommand(x, y, Widths[index], height, 0d, SoftBlue, Border, 0.45d));
            page.Add(new IoFatReportTextCommand(x + 5d, y - 14.5d, Widths[index] - 10d,
                headers[index], IoFatReportFontKind.Bold, 6.2d, Blue));
            x += Widths[index];
        }
        y -= height;
    }

    private static double GetPointRowHeight(IoTestPointPlan point)
    {
        var referenceLineCount = WrapReference(point.ReportIecReference).Count;
        return Math.Max(MinimumRowHeight, 12d + (referenceLineCount * 8.8d));
    }

    private static void DrawPointRow(
        List<IoFatReportCommand> page,
        IoTestPointPlan point,
        int rowNumber,
        double rowHeight,
        ref double y)
    {
        var cells = new[]
        {
            rowNumber.ToString(),
            Short(point.SignalName, 26),
            string.Empty,
            point.SignalKind.ToString(),
            ValueCell(point, FatValueSlot.Value1),
            ValueCell(point, FatValueSlot.Value2),
            point.CaptureMode == FatCaptureMode.OperatorSnapshot
                ? (point.IsFatEvidenceComplete ? "COMPLETE" : "PENDING")
                : point.Runtime.State switch
                {
                    IoTestPointState.Passed => "PASS",
                    IoTestPointState.Review => "REVIEW",
                    IoTestPointState.Failed => "FAILED",
                    _ => "PENDING"
                }
        };
        var resultColor = point.CaptureMode == FatCaptureMode.OperatorSnapshot
            ? (point.IsFatEvidenceComplete ? Pass : Muted)
            : point.Runtime.State switch
            {
                IoTestPointState.Passed => Pass,
                IoTestPointState.Review => Attention,
                IoTestPointState.Failed => Fail,
                _ => Muted
            };

        var x = Margin;
        for (var index = 0; index < cells.Length; index++)
        {
            page.Add(new IoFatReportRectCommand(x, y, Widths[index], rowHeight, 0d, White, Border, 0.35d));
            var color = index == cells.Length - 1 ? resultColor : Ink;
            var font = index is 0 or 2 ? IoFatReportFontKind.Mono : index is 1 or 6 ? IoFatReportFontKind.Bold : IoFatReportFontKind.Regular;

            if (index == 2)
            {
                var lineY = y - 11d;
                foreach (var referenceLine in WrapReference(point.ReportIecReference))
                {
                    page.Add(new IoFatReportTextCommand(
                        x + 5d,
                        lineY,
                        Widths[index] - 10d,
                        referenceLine,
                        IoFatReportFontKind.Mono,
                        5.35d,
                        Ink));
                    lineY -= 8.8d;
                }
            }
            else
            {
                page.Add(new IoFatReportTextCommand(x + 5d, y - 13d, Widths[index] - 10d, cells[index], font, 6.2d, color));
            }

            if (index is 4 or 5)
            {
                var stamp = ValueTimestamp(point, index == 4 ? FatValueSlot.Value1 : FatValueSlot.Value2);
                page.Add(new IoFatReportTextCommand(x + 5d, y - 26d, Widths[index] - 10d, stamp, IoFatReportFontKind.Mono, 5.45d, EvidenceMuted));
            }
            x += Widths[index];
        }
        y -= rowHeight;
    }

    private static IReadOnlyList<string> WrapReference(string? value)
    {
        var text = Clean(value);
        if (text.Length <= ReferenceCharsPerLine)
            return new[] { text };

        var lines = new List<string>();
        var offset = 0;
        while (offset < text.Length)
        {
            var take = Math.Min(ReferenceCharsPerLine, text.Length - offset);
            if (offset + take < text.Length)
            {
                var segment = text.AsSpan(offset, take);
                var split = segment.LastIndexOfAny('/', '.', '$');
                if (split >= ReferenceCharsPerLine / 2)
                    take = split + 1;
            }

            lines.Add(text.Substring(offset, take));
            offset += take;
        }
        return lines;
    }

    private static string ValueCell(IoTestPointPlan point, FatValueSlot slot)
        => Short(CanonicalReportValue(slot == FatValueSlot.Value1 ? point.Value1Text : point.Value2Text), 22);

    private static string CanonicalReportValue(string? value)
    {
        var text = Clean(value);
        if (text.Equals("true", StringComparison.OrdinalIgnoreCase))
            return "True";
        if (text.Equals("false", StringComparison.OrdinalIgnoreCase))
            return "False";
        return text;
    }

    private static string ValueTimestamp(IoTestPointPlan point, FatValueSlot slot)
    {
        var text = slot == FatValueSlot.Value1 ? point.Value1RelayTimestampText : point.Value2RelayTimestampText;
        return string.IsNullOrWhiteSpace(text) || text == "—" ? "IED time: -" : "IED " + Short(text, 24);
    }

    private static string Clean(string? value)
    {
        var normalized = (value ?? string.Empty).Replace('\r', ' ').Replace('\n', ' ').Trim();
        return normalized.Length == 0 ? "-" : normalized;
    }

    private static string Short(string? value, int maximum)
    {
        var clean = Clean(value);
        return clean.Length <= maximum ? clean : clean[..Math.Max(1, maximum - 1)] + "…";
    }

    private static string Short(string? value, int maximum, string fallback)
    {
        var clean = Clean(value);
        if (clean == "-")
            return fallback;
        return clean.Length <= maximum ? clean : clean[..Math.Max(1, maximum - 1)] + "…";
    }

    private static IoFatReportColor Color(string hex) => IoFatReportColor.FromHex(hex);
}
